FROM python:latest

COPY users/app.py/ users/
COPY users/users.sql/ users/
COPY key.txt/ users/

WORKDIR /users

RUN pip3 install flask
RUN pip3 install requests

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0"]