FROM python:latest

COPY availability/app.py/ availability/
COPY availability/availability.sql/ availability/
COPY key.txt/ availability/

WORKDIR /availability

RUN pip3 install flask
RUN pip3 install requests

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0"]