services:
  user:
    build:
      context: .
      dockerfile: users/Dockerfile.users
    ports:
      - "9000:5000"
    networks:
      - andronic
  availability:
    build:
      context: .
      dockerfile: availability/Dockerfile.availability
    ports:
      - "9001:5000"
    networks:
      - andronic
  reservations:
    build:
      context: .
      dockerfile: reservations/Dockerfile.reservations
    ports:
      - "9002:5000"
    networks:
      - andronic
  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile.payments
    ports:
      - "9003:5000"
    networks:
      - andronic

networks:
  andronic:
    driver: bridge


    